### PR TITLE
Stages 1 and 2: Setup to allow users to change SASS variables, implem…

### PR DESCRIPTION
**Pull request by adam-knights**
…ent validation when users are inputting via text directly

### CODE REVIEW

**Comment by adam-knights** [comment]
@DavidTytheridge @leeaustinbsc @adamlawson please review

**Comment by DavidTytheridge** [comment]
README.md - Remove the extra "you" line 19.

**Comment by adaml881** [comment]
Looks good to me

**Comment by leeaustinbsc** [comment]
looks okay

**Comment by DavidTytheridge** [comment]
Looks fabulous.

**Pull request merged**
