### PR TITLE
Stage 3: Add the datepicker pop out and allow dates to be selected

### PR DESCRIPTION
**Pull request by adam-knights**

### CODE REVIEW

**Comment by adam-knights** [comment]
@DavidTytheridge @adamlawson please review - tests will be added as stage 3b but wanted a review for when i get back off holiday - in the unlikely event your both have no changes, please merge pull request @DavidTytheridge

**Comment by adaml881** [comment]
All looks good to me

**Comment by adam-knights** [comment]
@DavidTytheridge review please

**Comment by DavidTytheridge** [comment]
Fine by me.

**Pull request merged**
